- name: '[AWS IAM Authenticator] Downloading'
  get_url:
    url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
    dest: ./aws-iam-authenticator
  when: ansible_os_family == 'Debian'

- name: '[AWS IAM Authenticator] Changing permissions'
  shell: chmod +x ./aws-iam-authenticator
  when: ansible_os_family == 'Debian'

- name: '[AWS IAM Authenticator] - Moving to bin'
  ansible.builtin.command: mv ./aws-iam-authenticator /usr/local/bin
  ignore_errors: true
  when: ansible_os_family == 'Debian'

- name: '[AWS IAM Authenticator] - Verifying version'
  shell: aws-iam-authenticator version
  register: out
  ignore_errors: true
  when: ansible_os_family == 'Debian'

- name: '[AWS IAM Authenticator] - Printing Version'
  debug:
    msg: "{{out.stdout_lines}}"