- name: Creating Setup Directory
  file: 
    path: /home/ubuntu/k8s_setup/
    state: directory

- name: Installing Kubernetes
  include_tasks: install-worker-k8s.yml

- name: Creating Persistent Volume Directory
  file: 
    path: /AppData
    state: directory
    mode: 0777

- name: Creating MySQL Persistent Volume Directory
  file: 
    path: /AppData/mysql
    state: directory
    mode: 0777

