- name: '[Java] - Updating Cache'
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: '[Java] - Installing'
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == 'Debian'

