- name: 'EKSCTL Playbook'
  hosts: [k8s_master_nodes]
  become: true  
  roles:
    - role: k8s-kubectl-role
    - role: eksctl-role
    - role: aws-iam-authenticator-role
    - role: unzip-role
    - role: aws-cli-role
