- name: 'Jenkins Playbook'
  hosts: [jenkins_nodes]
  become: true
  roles:
    - role: java-role
    - role: git-role
    - role: maven-role
    - role: docker-role
    - role: jenkins-role
    - role: aws-iam-authenticator-role
    - role: unzip-role
    - role: aws-cli-role
    - role: helm-role
